#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: '{{ name_vendor }} | Koffer | bundle.yml' 
  hosts: local
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "bundle"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    redhat_quay_pull_file: '{{ dir_artifacts }}/.docker/master.json }}'
  roles:
    - bundle
