#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: '{{ name_vendor }} | Koffer | images.yml' 
  hosts: local
  vars_files:
    - 'vars/global.yml'
    - 'vars/synker.yml'
  vars:
    module: "images"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:

    - name: '{{ ansible_name_module }} | file:absent | Purge Pre-Existing Artifacts' 
      file: 
        path: "{{ dir_deploy }}/deploy/mirror/docker"
        state: absent
    - name: '{{ ansible_name_module }} | file:directory | Place Artifacts Directory' 
      file: 
        path: "{{ dir_deploy }}/images"
        state: directory

    - name: '{{ ansible_name_module }} | command:skopeo.copy | Pull App Images | {{ url_registry_redhat_io }}' 
      command:
        argv:
          - skopeo
          - copy
          - --format=v2s2
          - 'docker://{{ url_registry_redhat_io }}/{{ item }}'
          - 'docker://localhost:5000/{{ item }}'
      with_items:
        - '{{ images_apps_redhat_io }}'

    - name: '{{ ansible_name_module }} | command:skopeo.copy | Pull App Images | {{ url_registry_redhat }} ' 
      command:
        argv:
          - skopeo
          - copy
          - --format=v2s2
          - 'docker://{{ url_registry_redhat }}/{{ item }}'
          - 'docker://localhost:5000/{{ item }}'
      with_items:
        - '{{ images_apps_redhat }}'

    - name: '{{ ansible_name_module }} | command:skopeo.copy | Pull App Images | {{ url_registry_docker }}' 
      command:
        argv:
          - skopeo
          - copy
          - --format=v2s2
          - 'docker://{{ url_registry_docker }}/{{ item }}'
          - 'docker://localhost:5000/{{ item }}'
      with_items:
        - '{{ images_apps_docker }}'

#   - name: '{{ ansible_name_module }} | command:skopeo.copy | Pull App Images | {{ url_registry_dsop }}' 
#     command:
#       argv:
#         - skopeo
#         - copy
#         - --format=v2s2
#         - 'docker://{{ url_registry_dsop }}/{{ item }}'
#         - 'docker://localhost:5000/{{ item }}'
#     with_items:
#       - '{{ images_apps_dsop }}'

    - name: '{{ ansible_name_module }} | command:skopeo.copy | Pull App Images | {{ url_registry_k8s }}' 
      command:
        argv:
          - skopeo
          - copy
          - --format=v2s2
          - 'docker://{{ url_registry_k8s }}/{{ item }}'
          - 'docker://localhost:5000/{{ item }}'
      with_items:
        - '{{ images_apps_k8s }}'

    - name: '{{ ansible_name_module }} | command:skopeo.copy | Pull App Images | {{ url_registry_quay }}' 
      command:
        argv:
          - skopeo
          - copy
          - --format=v2s2
          - 'docker://{{ url_registry_quay }}/{{ item }}'
          - 'docker://localhost:5000/{{ item }}'
      with_items:
        - '{{ images_apps_quay }}'
