---
- name: '{{ ansible_name_module }} | stat | check for mirror v2.sha256'
  stat:
    path: '{{ dir_deploy }}/mirror/v2.list.sha256'
  register: mirror_sha_check

###### Download OpenShift Docker Images from Quay.io to File: /root/deploy/mirror/v2
- name: '{{ ansible_name_module }} | block | Download OpenShift images'
  block:

  ######### Purge & Prepare
    - name: '{{ ansible_name_module }} | file:directory | Create mirror artifact directories'
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ dir_deploy }}/mirror"

# ######### Mirror Images to directory
#   - name: '{{ ansible_name_module }} | shell:registry.serve | Start Local Docker Registry Servie Port:5000'
#     shell: /usr/local/bin/run_registry.sh
#     shell: registry serve /etc/docker/registry/config.yml &

  ######### Mirror Images to directory
    - name: '{{ ansible_name_module }} | shell:oc.adm.release.mirror | Sync content from quay.io'
      shell: |
#       oc adm release mirror --insecure=true \
#         --to=localhost:5000/openshift-release-dev \
#         --registry-config=/root/.docker/config.json \
#         --from=quay.io/openshift-release-dev/ocp-release:{{ version_openshift }}-x86_64 \
#         --to-release-image=localhost:5000/openshift-release-dev:{{ version_openshift }}-x86_64

# TODO Integrate for OLM
	$OC adm catalog mirror localhost:5000/olm/redhat-operators:v1 localhost:5000 -a $LOCAL_SECRET_JSON --insecure
	$OC adm catalog build \
              --from=registry.redhat.io/openshift4/ose-operator-registry:v4.3 \
              --to=${LOCAL_REGISTRY}/olm/redhat-operators:v1 \
              --appregistry-org redhat-operators \
              --filter-by-os="linux/amd64" \
              -a ${LOCAL_SECRET_JSON} \
              --insecure

      when: image_mirror_utility == "oc"
 
  ######### Skopeo Copy Images to Registry
    - name: '{{ ansible_name_module }} | shell:skopeo.copy | Sync content from quay.io'
      shell: |
          for i in $(cat /var/lib/koffer/release.list); do \
            skopeo copy docker://quay.io/$i \
            docker://localhost:5000/$i ; \
          done
      when: image_mirror_utility == "skopeo"

  ####### Block Conditionals
  when: not mirror_sha_check.stat.exists

###### END OF BLOCK #######

- name: '{{ ansible_name_module }} | stat | sha256 mirror/v2 directory list'
  command:
    cmd: 'touch /root/deploy/mirror/v2.list.sha256'
  args:
    chdir: '/root/deploy/mirror/'
    warn: false

# name: '{{ ansible_name_module }} | stat | sha256 mirror/v2 directory list'
# command: 'find -type f ! -iname "sha256checksums" -exec sha256sum "{}" + > {{ local_home }}/deploy/mirror/v2.list.sha256'
# args:
#   chdir: /root/deploy/mirror/
