---
- name: '{{ ansible_name_module }} | stat | check for mirror v2.sha256'
  stat:
    path: '{{ dir_deploy }}/mirror/olm-catalog.redhat-operators.lock'
  register: mirror_redhat_operators_lock

###### Download OpenShift Docker Images from Quay.io to File: /root/deploy/mirror/v2
- name: '{{ ansible_name_module }} | block | Download OpenShift images'
  block:
   ######## Purge & Prepare
    - name: '{{ ansible_name_module }} | file:directory | Create mirror artifact directories'
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ dir_deploy }}/mirror"
   ######## Mirror Catalog to Registry
    - name: '{{ ansible_name_module }} | shell:oc.adm.catalog.mirror | Sync OLM Catalog'
      shell: |
        oc adm catalog mirror \
          -a /root/.docker/config.json --insecure \
          localhost:5000/olm/redhat-operators:v1 localhost:5000
      when: image_mirror_utility == "oc"
   ######## Mirror Catalog to Registry
    - name: '{{ ansible_name_module }} | shell:oc.adm.catalog.mirror | Mirror OLM RedHat Operator Images'
      shell: |
        oc adm catalog build --insecure=true \
          --registry-config=/root/.docker/config.json \
          --from=registry.redhat.io/openshift4/ose-operator-registry:v4.3 \
          --to=localhost:5000/olm/redhat-operators:v1 \
          --appregistry-org redhat-operators \
          --filter-by-os="linux/amd64"
      when: image_mirror_utility == "oc"
 
   ######## Skopeo Copy Images to Registry
    - name: '{{ ansible_name_module }} | shell:skopeo.copy | Sync content from quay.io'
      shell: |
          for i in $(cat /var/lib/koffer/release.list); do \
            skopeo copy docker://quay.io/$i \
            docker://localhost:5000/$i ; \
          done
      when: image_mirror_utility == "skopeo"

  ####### Block Conditionals
  when: not mirror_redhat_operators_lock.stat.exists

###### END OF BLOCK #######

- name: '{{ ansible_name_module }} | stat | sha256 mirror/v2 directory list'
  command:
    cmd: 'touch {{ dir_deploy }}/mirror/olm-catalog.redhat-operators.lock'
  args:
    chdir: '/root/deploy/mirror/'
    warn: false

# name: '{{ ansible_name_module }} | stat | sha256 mirror/v2 directory list'
# command: 'find -type f ! -iname "sha256checksums" -exec sha256sum "{}" + > {{ local_home }}/deploy/mirror/v2.list.sha256'
# args:
#   chdir: /root/deploy/mirror/
