---
- name: '{{ ansible_name_module }} | file:absent | Purge pre-existing operator bundles'
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - '{{ local_home }}/deploy/bundle/koffer-bundle.redhat-operators.tar'
    - '{{ local_home }}/deploy/bundle/koffer-bundle.redhat-operators.tar.sha256'

- name: '{{ ansible_name_module }} | command:tar | build tarball bundle of all artifacts'
  command:
    "tar -cv -f {{ local_home }}/deploy/bundle/koffer-bundle.redhat-operators.tar -C {{ local_home }}/deploy/mirror docker"
  args:
    creates: '{{ local_home }}/deploy/bundle/koffer-bundle.redhat-operators.tar'
    warn: false

- name: '{{ ansible_name_module }} | stat:sha256 | SHA koffer-bundle.redhat-operators.tar'
  command: 'sha256sum koffer-bundle.redhat-operators.tar'
  args:
    warn: false
    chdir: '{{ local_home }}/deploy/bundle'
  register: bundle_sha

- name: '{{ ansible_name_module }} | copy:content.sha256 | Create Sha256 Verification file'
  copy:
    content: '{{ bundle_sha.stdout }}'
    dest: '{{ local_home }}/deploy/bundle/koffer-bundle.redhat-operators.tar.sha256'
