---
####### Purge preexisting bundles
- name: '{{ ansible_name_module }} | file | Purge pre-existing bundles'
  file:
    path: '{{ local_home }}/deploy/bundle'
    state: directory

####### Purge preexisting bundles
- name: '{{ ansible_name_module }} | file | Purge pre-existing bundles'
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - '{{ local_home }}/deploy/bundle/koffer-bundle.redhat-operators.tar.xz'
    - '{{ local_home }}/deploy/bundle/koffer-bundle.redhat-operators.tar.xz.sha256'

####### Build Unified Bundle
- name: '{{ ansible_name_module }} | command:tar | build tarball bundle of all artifacts'
  command:
    "tar -c --use-compress-program='pigz -9 ' -v -f {{ local_home }}/deploy/bundle/koffer-bundle.redhat-operators.tar.xz -C {{ local_home }}/deploy/mirror docker"
  args:
    creates: '{{ local_home }}/deploy/bundle/koffer-bundle.redhat-operators.tar.xz'
    warn: false

####### SHA256sum koffer-bundle.redhat-operators.tar.xz
- name: '{{ ansible_name_module }} | stat:sha256 | SHA koffer-bundle.redhat-operators.tar.xz'
  command: 'sha256sum koffer-bundle.redhat-operators.tar.xz'
  args:
    warn: false
    chdir: '{{ local_home }}/deploy/bundle'
  register: bundle_sha

- name: '{{ ansible_name_module }} | copy:content.bcrypt_htpasswd | Generate Default Registry Basic Auth'
  copy:
    content: '{{ bundle_sha.stdout }}'
    dest: '{{ local_home }}/deploy/bundle/koffer-bundle.redhat-operators.tar.xz.sha256'

####### Build Unified Bundle
# name: '{{ ansible_name_module }} | command:tar.cvf | Build unified bundle with auxilary unpack+launch utilities'
# command:
#   "tar -cvf {{ local_home }}/koffer/bundle/koffer-bundle.openshift-{{ version_openshift  }}.tar -C /tmp koffer-bundle.redhat-operators.tar.xz.sha256 koffer-bundle.redhat-operators.tar.xz cloudctl.yml start-cloudctl.sh"
# args:
#   creates: "{{ local_home }}/deploy/bundle/koffer-bundle.redhat-operators.tar"
#   warn: false

# name: '{{ ansible_name_module }} | role | archive | Bundle koffer-bundle.redhat-operators.tar.xz with auxilary files'
# archive:
#   path:
#   - '/tmp/koffer-bundle.redhat-operators.tar.xz.sha256'
#   - '/tmp/koffer-bundle.redhat-operators.tar.xz'
#   - '/tmp/registry.yml'
#   - '/tmp/registry.sh'
#   dest: '{{ local_home }}/deploy/{{ cloud_provider }}-{{ target_environment }}-{{ name_cluster_vpc }}-p1bundle.tar'
#   format: tar
